## Downloading Anaconda

Link: https://www.anaconda.com/distribution/


## Getting used to Jupyter Notebook environment

1) Markdown vs. code
2) Save a notebook .ipynb vs .py
3) Run a cell, stop the cell


## Basic python commands

In [44]:
# This is how we comment and below is how we print
print("Hello, world!")

Hello, world!


In [46]:
# for loop
for i in range(5):
    if i > 3:
        print(True)
    else:
        print(False)
#Print

False
False
False
False
True


In [47]:
# while loop
i = 0
while i < 5:
    print(i)
    i = i + 1

0
1
2
3
4


## Python Data types

1) Numeric - integers, floats and complex numbers
2) Boolean - True or False
3) Sequences - strings, lists and tuples
4) Dictionary

More information: https://www.tutorialsteacher.com/python/python-data-types


In [51]:
a = 'T'

In [52]:
type(a)

str

In [53]:
b = [8,'a',13.49]

In [54]:
for i in b:
    print(type(i))

<class 'int'>
<class 'str'>
<class 'float'>


In [55]:
# Lists
c = ['John', 'Harry', 'Sean', 1, 6, 2]

In [58]:
c[-6]

'John'

In [ ]:
'Sean' in c

In [ ]:
# Dictionary
z = {'Name':'John', 'Age':32, 'Height': 169.24, 'colors': ['blue','orange','red']}

In [ ]:
z['colors']

z['colors'][1] = ?

In [59]:
a = [1, 2, 3, 4, 5, 6]
b = a*2

In [60]:
# Is this what you expected to happen?
b

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

Python's default list structure is for any type, not designed specifically for numeric operations

Need to use an additional package to do vector/matrix operations

## Importing packages
Packages give us additional functionality, saving us the trouble of writing procedures ourselves. There are ~6000 packages in the conda-forge repository alone!


## NumPy
We'll now import NumPy. NumPy provides high-performance multidimensional arrays and linear algebra operations (similar to Matlab). It is a fundamental package for scientific computing with Python.

More information: https://numpy.org/doc/1.18/user/index.html

In [61]:
import numpy as np

In [62]:
# NumPy arrays
a = np.array(a) # a is now a NumPy array
b = a*2

print(b)

[ 2  4  6  8 10 12]


In [63]:
c = np.array([[45,36,18,12],[53,90,56,62],[10,84,27,49]])

In [64]:
c

array([[45, 36, 18, 12],
       [53, 90, 56, 62],
       [10, 84, 27, 49]])

In [65]:
# Indexing
print(c[0, :])  # First row
print(c[:, 0])  # First column
print(c[1, 1])  # Second row, second column
print(c[1:3, :])  # Second rows

[45 36 18 12]
[45 53 10]
90
[[53 90 56 62]
 [10 84 27 49]]


### Arithmetical operations in Numpy

Information: https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html


In [71]:
# Get the minimum horizontally across columns (axis 1)
c.sum(axis=0)

array([108, 210, 101, 123])

In [72]:
print(c.sum(axis=1))  # sum across columns
print(c.sum())  # sum entire array

[111 261 170]
542


In [73]:
# Get the minimum horizontally across columns (axis 1)
c.max(axis=1)

array([45, 90, 84])

In [74]:
# Boolean operations
c > 40

array([[ True, False, False, False],
       [ True,  True,  True,  True],
       [False,  True, False,  True]])

In [68]:
c

array([[45, 36, 18, 12],
       [53, 90, 56, 62],
       [10, 84, 27, 49]])

In [75]:
c[c > 40]

array([45, 53, 90, 56, 62, 84, 49])

## Masked arrays

Information: https://docs.scipy.org/doc/numpy/reference/maskedarray.generic.html

Useful in working with no-data values like -9999


In [79]:
import numpy.ma as ma

In [80]:
d = ma.masked_greater(c, 40)
print(d)

[[-- 36 18 12]
 [-- -- -- --]
 [10 -- 27 --]]


## Pandas
A library to work with tabular data

Comparable to data frames in R

Pros:
You can name columns and refence by labels instead of numeric indices like in NumPy arrays
This also makes performing group operations easier and more readable

Cons:
Designed for tabular data, not for dimensions > 2. We will cover xarray for N-dimensional data later.

More information: https://pandas.pydata.org/docs/user_guide/index.html


In [82]:
import pandas as pd

In [83]:
precip = pd.read_csv('amazon_mm_precip.csv',index_col=['Lon','Lat'])

In [78]:
precip

2002-04-30  2002-05-31  2002-06-30  2002-07-31  2002-08-31  \
Lon     Lat                                                                   
-64.125 -20.625   79.617255    9.433339    4.925123   12.054081    3.811655   
-63.875 -20.625   65.950869   10.009700    3.501980   12.501568    0.721699   
-63.625 -20.625   42.593678   11.401450    3.477341   15.539033    0.445975   
-64.625 -20.375   38.521564    7.335321    5.157535    9.400707    6.439258   
-64.375 -20.375   54.486759    8.698377    5.521790   12.837736    4.926943   
...                     ...         ...         ...         ...         ...   
-60.875  5.375   247.044067  322.819841  516.566248  203.543229  240.019512   
-60.625  5.375   219.792416  333.701692  500.805888  181.378591  213.900139   
-60.375  5.375   216.497548  328.663967  500.260220  202.635140  213.882308   
-60.125  5.375   211.313932  332.940803  538.689451  242.273340  256.384141   
-59.875  5.375   275.869811  463.028970  630.921092  330.497503  309.537349   

                 2002-09-30  2002-10-31  2002-11-30  2002-12-31  2003-01-31  \
Lon     Lat                                                                   
-64.125 -20.625   10.510660  109.748719   90.595858   68.959647  203.789907   
-63.875 -20.625    4.570555   96.606538   69.923118   68.520538  205.035310   
-63.625 -20.625    3.623671   83.898189   57.269862   54.668323  162.208639   
-64.625 -20.375   12.508164   91.335901   60.776228   63.164483  128.729435   
-64.375 -20.375   13.153420   97.969218   69.843489   72.605402  165.918521   
...                     ...         ...         ...         ...         ...   
-60.875  5.375   101.853218   83.003125  173.398612   92.148600   21.772724   
-60.625  5.375   112.403258   61.099788  136.333970   92.928715   25.174881   
-60.375  5.375    88.453090   43.310798  141.830750   90.307059   39.100953   
-60.125  5.375    91.953903   40.327495  172.462596  127.807109   60.935964   
-59.875  5.375   107.416645   53.574641  304.071286  260.588429  167.646507   

                 ...  2018-10-31  2018-11-30  2018-12-31  2019-01-31  \
Lon     Lat      ...                                                   
-64.125 -20.625  ...   60.649257   62.391416  164.913497   89.878480   
-63.875 -20.625  ...   65.945193   47.922363  167.403595  106.832514   
-63.625 -20.625  ...   65.989691   42.139081  146.484994   86.216288   
-64.625 -20.375  ...   47.907756   68.862294  142.121565   87.041250   
-64.375 -20.375  ...   51.248163   66.856785  159.874002   77.698976   
...              ...         ...         ...         ...         ...   
-60.875  5.375   ...  198.639207  185.619657  117.693808  103.279413   
-60.625  5.375   ...  174.159157  175.571136  118.156307  107.723629   
-60.375  5.375   ...  112.441978  189.763992  125.442731  119.528364   
-60.125  5.375   ...   81.820802  182.869749  147.818770  142.943405   
-59.875  5.375   ...  118.449987  225.439711  205.753713  202.360096   

                 2019-02-28  2019-03-31  2019-04-30  2019-05-31  2019-06-30  \
Lon     Lat                                                                   
-64.125 -20.625  195.208941  216.730878   69.726078   16.832899   27.111787   
-63.875 -20.625  195.063715  199.724708   98.732243   17.818087   48.613059   
-63.625 -20.625  168.260787  207.539291  105.858625   20.313694   46.873625   
-64.625 -20.375  132.638025  160.959771   57.440456   11.069538   10.095330   
-64.375 -20.375  162.359272  213.465772   62.435963   13.512650   12.026635   
...                     ...         ...         ...         ...         ...   
-60.875  5.375    76.907977   82.014452  136.425669  293.101094  325.062275   
-60.625  5.375    81.728443   82.433510  131.207120  256.678498  283.520930   
-60.375  5.375    88.266456   91.154165  136.754712  320.606825  259.315903   
-60.125  5.375   106.174525  100.861326  153.248527  372.025008  291.233439   
-59.875  5.375   150.990450  137.302183  216.055241  449.922838  413.497281 

In [84]:
precip.head

<bound method NDFrame.head of                  2002-04-30  2002-05-31  2002-06-30  2002-07-31  2002-08-31  \
Lon     Lat                                                                   
-64.125 -20.625   79.617255    9.433339    4.925123   12.054081    3.811655   
-63.875 -20.625   65.950869   10.009700    3.501980   12.501568    0.721699   
-63.625 -20.625   42.593678   11.401450    3.477341   15.539033    0.445975   
-64.625 -20.375   38.521564    7.335321    5.157535    9.400707    6.439258   
-64.375 -20.375   54.486759    8.698377    5.521790   12.837736    4.926943   
...                     ...         ...         ...         ...         ...   
-60.875  5.375   247.044067  322.819841  516.566248  203.543229  240.019512   
-60.625  5.375   219.792416  333.701692  500.805888  181.378591  213.900139   
-60.375  5.375   216.497548  328.663967  500.260220  202.635140  213.882308   
-60.125  5.375   211.313932  332.940803  538.689451  242.273340  256.384141   
-59.875  5.375   275.8

In [85]:
precip.describe

<bound method NDFrame.describe of                  2002-04-30  2002-05-31  2002-06-30  2002-07-31  2002-08-31  \
Lon     Lat                                                                   
-64.125 -20.625   79.617255    9.433339    4.925123   12.054081    3.811655   
-63.875 -20.625   65.950869   10.009700    3.501980   12.501568    0.721699   
-63.625 -20.625   42.593678   11.401450    3.477341   15.539033    0.445975   
-64.625 -20.375   38.521564    7.335321    5.157535    9.400707    6.439258   
-64.375 -20.375   54.486759    8.698377    5.521790   12.837736    4.926943   
...                     ...         ...         ...         ...         ...   
-60.875  5.375   247.044067  322.819841  516.566248  203.543229  240.019512   
-60.625  5.375   219.792416  333.701692  500.805888  181.378591  213.900139   
-60.375  5.375   216.497548  328.663967  500.260220  202.635140  213.882308   
-60.125  5.375   211.313932  332.940803  538.689451  242.273340  256.384141   
-59.875  5.375   2

In [86]:
precip.index

MultiIndex([(-64.125, -20.625),
            (-63.875, -20.625),
            (-63.625, -20.625),
            (-64.625, -20.375),
            (-64.375, -20.375),
            (-64.125, -20.375),
            (-63.875, -20.375),
            (-63.625, -20.375),
            (-63.375, -20.375),
            (-63.125, -20.375),
            ...
            (-60.625,   5.125),
            (-60.375,   5.125),
            (-60.125,   5.125),
            (-59.875,   5.125),
            (-59.625,   5.125),
            (-60.875,   5.375),
            (-60.625,   5.375),
            (-60.375,   5.375),
            (-60.125,   5.375),
            (-59.875,   5.375)],
           names=['Lon', 'Lat'], length=8331)

In [87]:
precip.columns

Index(['2002-04-30', '2002-05-31', '2002-06-30', '2002-07-31', '2002-08-31',
       '2002-09-30', '2002-10-31', '2002-11-30', '2002-12-31', '2003-01-31',
       ...
       '2018-10-31', '2018-11-30', '2018-12-31', '2019-01-31', '2019-02-28',
       '2019-03-31', '2019-04-30', '2019-05-31', '2019-06-30', '2019-07-31'],
      dtype='object', length=208)

In [88]:
precip.columns = pd.to_datetime(precip.columns)

In [91]:
precip.columns[0].year

2002

In [94]:
precip.iloc[:,0]

Lon      Lat    
-64.125  -20.625     79.617255
-63.875  -20.625     65.950869
-63.625  -20.625     42.593678
-64.625  -20.375     38.521564
-64.375  -20.375     54.486759
                       ...    
-60.875   5.375     247.044067
-60.625   5.375     219.792416
-60.375   5.375     216.497548
-60.125   5.375     211.313932
-59.875   5.375     275.869811
Name: 2002-04-30 00:00:00, Length: 8331, dtype: float64

In [96]:
precip.loc[:]['2002-04-30']

Lon      Lat    
-64.125  -20.625     79.617255
-63.875  -20.625     65.950869
-63.625  -20.625     42.593678
-64.625  -20.375     38.521564
-64.375  -20.375     54.486759
                       ...    
-60.875   5.375     247.044067
-60.625   5.375     219.792416
-60.375   5.375     216.497548
-60.125   5.375     211.313932
-59.875   5.375     275.869811
Name: 2002-04-30 00:00:00, Length: 8331, dtype: float64

In [90]:
precip_mean = precip.mean(axis = 0, skipna = True)

In [ ]:
precip_mean